### ISSUE TITLE
Does line 120 actually do anything?

### ISSUE THREAD

**Issue by bogdanr** [volca/abutton-arduino#2]
I like this port of the AButton code but I am trying to understand if [line 120](https://github.com/volca/abutton-arduino/blob/defe6705abb44c35cba3bc518e0cd81e1e465146/src/src.ino#L120) actually does something.

Can you please enlighten me what does it actually do?

**Comment by volca** [comment]
It changes the color for led to blue. The other function `blinkHandler` calls setLed and change the color.

**Comment by bogdanr** [comment]
Yeah, I got that but blinkHandler doesn't seem to be called anywhere after the blue color is set.

**Comment by volca** [comment]
It's called by this line

```
    mBlink.attach(1, blinkHandler);
```

The Ticker will call the function per second.

**Comment by bogdanr** [comment]
Yeah, but as I see it, that happens before setting the color blue so the LED would never light blue. Did I get this right?

**Comment by volca** [comment]
Please try to change the color to another value

```
    mLedColor = pixels.Color(0, 255, 0);
```
